Traceback (most recent call last):
  File "/nfs/stak/users/cervanj2/cs340/cs340-Portfolio-Project/app.py", line 293, in ordersynthesizer
    line_price = int(unit_price) * int(quantity)
ValueError: invalid literal for int() with base 10: '22.22'
Traceback (most recent call last):
  File "/nfs/stak/users/cervanj2/cs340/cs340-Portfolio-Project/app.py", line 293, in ordersynthesizer
    line_price = int(unit_price) * int(quantity)
ValueError: invalid literal for int() with base 10: '33.33'
Traceback (most recent call last):
  File "/nfs/stak/users/cervanj2/cs340/cs340-Portfolio-Project/app.py", line 310, in ordersynthesizer
    newOrderPrice = (previousOrderPrice - previousOrderSynthesizerPrice) + line_price
TypeError: unsupported operand type(s) for +: 'decimal.Decimal' and 'float'
Traceback (most recent call last):
  File "/nfs/stak/users/cervanj2/cs340/cs340-Portfolio-Project/app.py", line 288, in ordersynthesizer
    orderSynthesizerID = request.form["orderSynthesizerID"]
  File "/nfs/stak/users/cervanj2/cs340/cs340-Portfolio-Project/venv/lib64/python3.9/site-packages/werkzeug/datastructures/structures.py", line 196, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/nfs/stak/users/cervanj2/cs340/cs340-Portfolio-Project/app.py", line 289, in ordersynthesizer
    orderID = request.form["orderID"]
  File "/nfs/stak/users/cervanj2/cs340/cs340-Portfolio-Project/venv/lib64/python3.9/site-packages/werkzeug/datastructures/structures.py", line 196, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/nfs/stak/users/cervanj2/cs340/cs340-Portfolio-Project/app.py", line 289, in ordersynthesizer
    orderID = request.form["orderID"]
  File "/nfs/stak/users/cervanj2/cs340/cs340-Portfolio-Project/venv/lib64/python3.9/site-packages/werkzeug/datastructures/structures.py", line 196, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/nfs/stak/users/cervanj2/cs340/cs340-Portfolio-Project/app.py", line 289, in ordersynthesizer
    orderID = request.form["orderID"]
  File "/nfs/stak/users/cervanj2/cs340/cs340-Portfolio-Project/venv/lib64/python3.9/site-packages/werkzeug/datastructures/structures.py", line 196, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/nfs/stak/users/cervanj2/cs340/cs340-Portfolio-Project/app.py", line 288, in ordersynthesizer
    orderSynthesizerID, orderID = synthOrderId.split(',')
NameError: name 'synthOrderId' is not defined
Traceback (most recent call last):
  File "/nfs/stak/users/cervanj2/cs340/cs340-Portfolio-Project/app.py", line 288, in ordersynthesizer
    orderSynthesizerID, orderID = orderSynthesizerID.split(',')
UnboundLocalError: local variable 'orderSynthesizerID' referenced before assignment
Traceback (most recent call last):
  File "/nfs/stak/users/cervanj2/cs340/cs340-Portfolio-Project/app.py", line 288, in ordersynthesizer
    orderSynthesizerID, orderID = synthOrderID.split(',')
NameError: name 'synthOrderID' is not defined
Traceback (most recent call last):
  File "/nfs/stak/users/cervanj2/cs340/cs340-Portfolio-Project/app.py", line 288, in ordersynthesizer
    synthOrderId = request.form["synthOrderId"]
  File "/nfs/stak/users/cervanj2/cs340/cs340-Portfolio-Project/venv/lib64/python3.9/site-packages/werkzeug/datastructures/structures.py", line 196, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/nfs/stak/users/cervanj2/cs340/cs340-Portfolio-Project/app.py", line 288, in ordersynthesizer
    synthOrderId = request.form["synthOrderId"]
  File "/nfs/stak/users/cervanj2/cs340/cs340-Portfolio-Project/venv/lib64/python3.9/site-packages/werkzeug/datastructures/structures.py", line 196, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/nfs/stak/users/cervanj2/cs340/cs340-Portfolio-Project/app.py", line 289, in ordersynthesizer
    orderSynthesizerID, orderID = synthOrderID.split(',')
NameError: name 'synthOrderID' is not defined
Traceback (most recent call last):
  File "/nfs/stak/users/cervanj2/cs340/cs340-Portfolio-Project/app.py", line 359, in purchases
    cur = mysql.connection.cursor()
  File "/nfs/stak/users/cervanj2/cs340/cs340-Portfolio-Project/venv/lib64/python3.9/site-packages/flask_mysqldb/__init__.py", line 109, in connection
    ctx.mysql_db = self.connect
  File "/nfs/stak/users/cervanj2/cs340/cs340-Portfolio-Project/venv/lib64/python3.9/site-packages/flask_mysqldb/__init__.py", line 97, in connect
    return MySQLdb.connect(**kwargs)
  File "/nfs/stak/users/cervanj2/cs340/cs340-Portfolio-Project/venv/lib64/python3.9/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "/nfs/stak/users/cervanj2/cs340/cs340-Portfolio-Project/venv/lib64/python3.9/site-packages/MySQLdb/connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to local server through socket '/var/lib/mysql/mysql.sock' (2)")
Traceback (most recent call last):
  File "/nfs/stak/users/cervanj2/cs340/cs340-Portfolio-Project/app.py", line 361, in purchases
    cur = mysql.connection.cursor()
NameError: name 'mysql' is not defined
Traceback (most recent call last):
  File "/nfs/stak/users/cervanj2/cs340/cs340-Portfolio-Project/app.py", line 364, in purchases
    cur = mysql.connection.cursor()
  File "/nfs/stak/users/cervanj2/cs340/cs340-Portfolio-Project/venv/lib64/python3.9/site-packages/flask_mysqldb/__init__.py", line 109, in connection
    ctx.mysql_db = self.connect
  File "/nfs/stak/users/cervanj2/cs340/cs340-Portfolio-Project/venv/lib64/python3.9/site-packages/flask_mysqldb/__init__.py", line 97, in connect
    return MySQLdb.connect(**kwargs)
  File "/nfs/stak/users/cervanj2/cs340/cs340-Portfolio-Project/venv/lib64/python3.9/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "/nfs/stak/users/cervanj2/cs340/cs340-Portfolio-Project/venv/lib64/python3.9/site-packages/MySQLdb/connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to server on 'classwork.engr.oregonstate.edu' (115)")
Traceback (most recent call last):
  File "/nfs/stak/users/cervanj2/cs340/cs340-Portfolio-Project/app.py", line 390, in purchases
    cur.execute(query, (manufacturer, name, price, signal, keyboard))
UnboundLocalError: local variable 'query' referenced before assignment
Traceback (most recent call last):
  File "/nfs/stak/users/cervanj2/cs340/cs340-Portfolio-Project/app.py", line 390, in purchases
    cur.execute(queryPurchases, (manufacturer, name, price, signal, keyboard))
NameError: name 'manufacturer' is not defined
